export { default as DuiButton } from './stories/Forms/DuiButton.vue'
export { default as DuiInput } from './stories/Forms/DuiInput.vue'
export { default as DuiTextarea } from './stories/Forms/DuiTextarea.vue'
export { default as DuiAction } from './stories/Elements/DuiAction.vue'
import './style.css'